CREATE TABLE `gallery` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `href` varchar(345) DEFAULT NULL,
  `img` varchar(345) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1